### ISSUE TITLE
getAssets should return asset precision

### ISSUE THREAD

**Issue by rraallvv** [nimiq/fastspot-api#2]
Sorry if this is a feature but it seems the amount returned by `getEstimate` is denominated in the smallest unit, Luna, Satoshi, or cents (for EUR). At first it seems a bit unintuitive since one might expect that asking an estimate for NIM, would return NIM as units and not Luna, or EUR in the case of euros and not cents. But then after giving some thought, it seems most APIs in the crypto world work using the smallest denomination as units for all assets so my only concern would be that the API doesn't have a way to retrieve the precision of an asset (smallest unit) to have certain level of agnosticism regarding the kind of assets that are used in the app.

**Comment by sisou** [comment]
Thanks @rraallvv, I just published v1.5.3 that exports a `Precision` dictionary that maps the asset to its number of decimals.
